fix(tasks): Remove unused worker_name var
Forgot to remove the argument passed to the ffmpeg run call from tasks.
It was throwing:

TypeError: run() got an unexpected keyword argument 'worker_name'